-- 029 补齐缺失字段
-- 为已存在的表添加代码中使用的缺失字段

-- 1. users 表添加 notification_settings
ALTER TABLE users ADD COLUMN IF NOT EXISTS notification_settings JSONB DEFAULT '{}'::jsonb;

-- 2. trades 表添加缺失字段
ALTER TABLE trades ADD COLUMN IF NOT EXISTS entry_fee DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS exit_fee DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS slippage_bps DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS slippage_cost DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS gross_pnl DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS net_pnl DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS margin DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS close_reason VARCHAR(50);

-- 3. positions 表添加缺失字段
ALTER TABLE positions ADD COLUMN IF NOT EXISTS fee DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE positions ADD COLUMN IF NOT EXISTS slippage_bps DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE positions ADD COLUMN IF NOT EXISTS slippage_cost DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE positions ADD COLUMN IF NOT EXISTS margin DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE positions ADD COLUMN IF NOT EXISTS realized_pnl DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE positions ADD COLUMN IF NOT EXISTS notional DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE positions ADD COLUMN IF NOT EXISTS opened_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE positions ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ;
ALTER TABLE positions ADD COLUMN IF NOT EXISTS close_price DOUBLE PRECISION;
ALTER TABLE positions ADD COLUMN IF NOT EXISTS close_fee DOUBLE PRECISION DEFAULT 0.0;

-- 4. data_quality_snapshots 表添加 created_at
ALTER TABLE data_quality_snapshots ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- 5. ticker_history 表添加 created_at 并修改时间戳类型
ALTER TABLE ticker_history ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE ticker_history ALTER COLUMN timestamp TYPE TIMESTAMPTZ USING timestamp AT TIME ZONE 'UTC';
ALTER TABLE ticker_history ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at AT TIME ZONE 'UTC';

-- 6. klines 表修改时间戳类型
ALTER TABLE klines ALTER COLUMN open_time TYPE TIMESTAMPTZ USING open_time AT TIME ZONE 'UTC';
ALTER TABLE klines ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at AT TIME ZONE 'UTC';
ALTER TABLE klines ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at AT TIME ZONE 'UTC';

-- 7. funding_rate_history 表修改时间戳类型
ALTER TABLE funding_rate_history ALTER COLUMN funding_time TYPE TIMESTAMPTZ USING funding_time AT TIME ZONE 'UTC';
ALTER TABLE funding_rate_history ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at AT TIME ZONE 'UTC';

-- 8. debate_sessions 表添加 market_snapshot
ALTER TABLE debate_sessions ADD COLUMN IF NOT EXISTS market_snapshot JSONB;

-- 9. ai_simulation_configs 表添加缺失字段
ALTER TABLE ai_simulation_configs ADD COLUMN IF NOT EXISTS analysis_interval VARCHAR(10) NOT NULL DEFAULT '1H';
ALTER TABLE ai_simulation_configs ADD COLUMN IF NOT EXISTS autonomous_config JSONB;
